---
- name: Install and configure Prometheus Node Exporter
  hosts: all
  become: yes
  tasks:
    - name: Download Node Exporter tarball
      ansible.builtin.get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.9.0/node_exporter-1.9.0.linux-amd64.tar.gz
        dest: /tmp/node_exporter-1.9.0.linux-amd64.tar.gz
        mode: '0644'

    - name: Extract Node Exporter tarball
      ansible.builtin.unarchive:
        src: /tmp/node_exporter-1.9.0.linux-amd64.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Move node_exporter binary to /usr/local/bin/
      ansible.builtin.command:
        cmd: mv /tmp/node_exporter-1.9.0.linux-amd64/node_exporter /usr/local/bin/
      args:
        creates: /usr/local/bin/node_exporter

    - name: Set executable permissions on node_exporter binary
      ansible.builtin.file:
        path: /usr/local/bin/node_exporter
        mode: '0755'

    - name: Create node_exporter user
      ansible.builtin.user:
        name: node_exporter
        shell: /bin/false
        system: yes
        create_home: no

    - name: Create systemd service file for node_exporter
      ansible.builtin.copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          User=node_exporter
          Group=node_exporter
          Type=simple
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable node_exporter service
      ansible.builtin.systemd:
        name: node_exporter
        enabled: yes

    - name: Start node_exporter service
      ansible.builtin.systemd:
        name: node_exporter
        state: started

    - name: Show node_exporter service status
      ansible.builtin.command:
        cmd: systemctl status node_exporter
      register: node_exporter_status
      ignore_errors: yes

    - name: Display node_exporter service status
      ansible.builtin.debug:
        var: node_exporter_status.stdout
